name: Prueba123
favicon: null
layout_spectrum: 0.10186515818350017
typography_spectrum: 0.6378730034921318
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#fc814c'
    - '#000000'
    - '#893e21'
    - '#00ab00'
  brandStrength: 0.7007793425582349
  lightness: 0.15137654566206038
  saturation: 0.34318716055713594
  rhythmicContrast: 0.6748615670949221
purpose: []
